[env:lolin32]
platform = espressif32
board = lolin32 
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; Файловая система
board_build.filesystem = littlefs 
 ; Увеличиваем размер файловой системы
board_build.partitions = custom.csv
; === УДАЛЕНЫ флаги Native USB ===

; === КРИТИЧЕСКИЙ ФИКС: Отключаем автоматический Reset/Bootloader при подключении монитора ===
monitor_rts = 0
monitor_dtr = 0

lib_deps = 
    ; === NEXT-GEN HTTP SERVER (PsychicHttp) ===
    ;hoeken/PsychicHttp@^1.4.0        ; Стабильный, актуальный PsychicHttp
    https://github.com/hoeken/PsychicHttp.git
    ArduinoJson@^7.0.0               ; Переход на более быструю и экономную версию 7.x
    LittleFS@^2.0.0

   