package com.bizard.homesmokemqtt.legacy;

import android.app.Notification;
import android.app.PendingIntent;
import android.app.Service;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.bluetooth.BluetoothSocket;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Binder;
import android.os.Build;
import android.os.Handler;
import android.os.IBinder;
import android.os.Looper;
import android.os.SystemClock;
import com.bizard.homesmokecore.AutoEngine;
import com.bizard.homesmokecore.AutoProgram;
import com.bizard.homesmokecore.ProtocolRules;
import com.bizard.homesmokecore.Telemetry;
import com.bizard.homesmokecore.TelemetryParser;
import org.json.JSONObject;
import java.io.EOFException;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.nio.charset.Charset;
import java.util.List;
import java.util.UUID;

/** Android 4 control service. Same AutoEngine and wire protocol, legacy platform APIs only. */
public class LegacyHomeSmokeService extends Service {
    interface Listener{void onState(State s);}static final class State{final boolean bt,mqtt;final String btName,mqttText,auto,lastError;final Telemetry t;final AutoEngine.State autoState;State(boolean b,boolean m,String n,String mt,String a,String e,Telemetry t,AutoEngine.State s){bt=b;mqtt=m;btName=n;mqttText=mt;auto=a;lastError=e;this.t=t;autoState=s;}}
    private static final Charset UTF8=Charset.forName("UTF-8");private static final UUID SPP=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");private static final String END="\\0";private static final int NOTIFY=261;
    final class LocalBinder extends Binder{LegacyHomeSmokeService getService(){return LegacyHomeSmokeService.this;}}private final IBinder binder=new LocalBinder();private final Handler main=new Handler(Looper.getMainLooper());private final StringBuilder rx=new StringBuilder();private final AutoEngine engine=new AutoEngine();private SharedPreferences prefs;private BluetoothSocket socket;private Thread btThread;private MqttClient mqtt;private boolean mqttWanted,mqttConnecting,client;private Listener listener;private Telemetry latest;private String btName="",mqttText="MQTT отключен",autoText="Auto выключено",error="";private String pendingId="";private double pendingValue;private long pendingSince;
    private final Runnable heartbeat=new Runnable(){public void run(){if(engine.getState()!=AutoEngine.State.RUNNING)return;if(!send("h")){abort("Bluetooth потерян");return;}main.postDelayed(this,2000);}};private final Runnable mqttHealth=new Runnable(){public void run(){if(mqttWanted&&!mqttConnected()&&!mqttConnecting)connectMqtt();main.postDelayed(this,5000);}};
    @Override public void onCreate(){super.onCreate();prefs=getSharedPreferences("homesmoke_full",MODE_PRIVATE);main.postDelayed(mqttHealth,5000);}
    @Override public IBinder onBind(Intent i){client=true;return binder;}@Override public boolean onUnbind(Intent i){client=false;maybeStop();return true;}@Override public void onRebind(Intent i){client=true;super.onRebind(i);}@Override public int onStartCommand(Intent i,int f,int id){return START_STICKY;}
    void setListener(Listener l){listener=l;emit();}State state(){return snap();}boolean btConnected(){return socket!=null&&socket.isConnected();}boolean mqttConnected(){return mqtt!=null&&mqtt.isConnected();}boolean autoRunning(){return engine.getState()==AutoEngine.State.RUNNING;}
    void connectBt(final String address){closeBt();btThread=new Thread(new Runnable(){public void run(){try{BluetoothAdapter a=BluetoothAdapter.getDefaultAdapter();if(a==null)throw new IOException("Bluetooth не поддерживается");BluetoothDevice d=a.getRemoteDevice(address);BluetoothSocket s=d.createRfcommSocketToServiceRecord(SPP);socket=s;s.connect();btName=d.getName()==null?address:d.getName();main.post(new Runnable(){public void run(){error="";emit();}});read(s.getInputStream());}catch(final Exception e){main.post(new Runnable(){public void run(){error="Bluetooth: "+msg(e);emit();}});}finally{closeBtInternal();if(autoRunning())abort("Bluetooth потерян");main.post(new Runnable(){public void run(){emit();}});}}},"HomeSmokeLegacy-BT");btThread.start();}
    void disconnectBt(){if(autoRunning())stopAuto("Bluetooth отключён");closeBt();emit();}
    boolean manual(){if(autoRunning())stopAuto("Ручной режим");return send("a0");}boolean pid(){if(autoRunning())stopAuto("PID режим");return send("a1");}boolean stopHeating(){main.removeCallbacks(heartbeat);if(autoRunning()){AutoEngine.Update u=engine.stop("СТОП");commands(u.commands);}else{send("a3");send("x0");}autoText="ТЭН выключен";stopForeground(true);emit();maybeStop();return true;}boolean setTemp(double v){return ProtocolRules.isPercentOrChamberSetpoint(v)&&send("k"+(int)Math.rint(v));}boolean setPower(double v){return ProtocolRules.isPercentOrChamberSetpoint(v)&&send("v"+(int)Math.rint(v));}boolean setPid(String prefix,String raw){try{String x=new BigDecimal(raw.replace(',','.')).multiply(new BigDecimal("100")).stripTrailingZeros().toPlainString();return send(prefix+x);}catch(Exception e){return false;}}
    boolean startAuto(AutoProgram p){if(!btConnected()){error="Для Auto нужен Bluetooth";emit();return false;}try{startService(new Intent(this,LegacyHomeSmokeService.class));AutoEngine.Update u=engine.start(p,SystemClock.elapsedRealtime());if(!commands(u.commands)){engine.stop("Ошибка запуска");send("a3");send("x0");return false;}autoText=u.message;startForeground(NOTIFY,notification());main.removeCallbacks(heartbeat);main.postDelayed(heartbeat,2000);emit();return true;}catch(Exception e){error=msg(e);emit();return false;}}
    void stopAuto(String why){main.removeCallbacks(heartbeat);commands(engine.stop(why).commands);autoText=why;stopForeground(true);emit();maybeStop();}
    void mqttConfig(String host,String port,String status,String cmd,String ack,String user,String pass,boolean tls,boolean auto){prefs.edit().putString("broker",host.trim()).putString("port",port.trim()).putString("topic",status.trim()).putString("cmd_topic",cmd.trim()).putString("ack_topic",ack.trim()).putString("user",user).putString("pass",pass).putBoolean("tls",tls).putBoolean("mqtt_auto",auto).apply();}void startMqtt(){startService(new Intent(this,LegacyHomeSmokeService.class));mqttWanted=true;connectMqtt();}void stopMqtt(){mqttWanted=false;MqttClient m=mqtt;mqtt=null;if(m!=null)m.close();mqttText="MQTT отключен";emit();maybeStop();}
    private void connectMqtt(){if(mqttConnecting||mqttConnected())return;final String host=prefs.getString("broker","").trim();if(host.length()==0){mqttText="Broker не задан";emit();return;}final int port;try{port=Integer.parseInt(prefs.getString("port","1883"));}catch(Exception e){mqttText="Неверный port";emit();return;}mqttConnecting=true;mqttText="MQTT подключение…";emit();new Thread(new Runnable(){public void run(){final MqttClient c=new MqttClient(host,port,prefs.getBoolean("tls",false),prefs.getString("user",""),prefs.getString("pass",""));c.setMessageListener(new MqttClient.MessageListener(){public void onMessage(String topic,String payload){mqttMessage(topic,payload);}});try{c.connect();c.subscribe(cmdTopic());mqtt=c;mqttConnecting=false;mqttText="MQTT подключен";main.post(new Runnable(){public void run(){emit();}});}catch(final Exception e){c.close();mqttConnecting=false;mqttText="MQTT: "+msg(e);main.postDelayed(new Runnable(){public void run(){if(mqttWanted)connectMqtt();}},10000);}}},"HomeSmokeLegacy-MQTT-connect").start();}
    private void mqttMessage(String topic,String payload){if(!cmdTopic().equals(topic))return;try{JSONObject o=new JSONObject(payload);String cmd=o.optString("cmd","");String id=o.optString("id","legacy-"+System.currentTimeMillis());if("set_temp".equals(cmd)){double v=o.getDouble("value");if(!ProtocolRules.isPercentOrChamberSetpoint(v)){ack(id,cmd,false,"integer_setpoint_0_100_required",v);return;}if(autoRunning()){ack(id,cmd,false,"android_auto_running",v);return;}if(latest==null||latest.mode!=1){ack(id,cmd,false,"pid_mode_required",v);return;}if(send("k"+(int)Math.rint(v))){pendingId=id;pendingValue=v;pendingSince=SystemClock.elapsedRealtime();ack(id,cmd,true,"accepted_waiting_controller",v);}else ack(id,cmd,false,"bluetooth_send_error",v);}else if("stop".equals(cmd)){stopHeating();ack(id,cmd,true,"stop_sent",Double.NaN);}}catch(Exception ignored){}}
    private void read(InputStream in)throws IOException{byte[] b=new byte[512];while(!Thread.currentThread().isInterrupted()){int n=in.read(b);if(n<0)throw new EOFException();if(n>0)synchronized(rx){rx.append(new String(b,0,n,UTF8));extract();}}}private void extract(){while(true){int e=rx.indexOf("end");if(e<0){if(rx.length()>8192)rx.delete(0,rx.length()-4096);return;}String f=rx.substring(0,e+3);rx.delete(0,e+3);while(rx.length()>0&&(rx.charAt(0)=='\r'||rx.charAt(0)=='\n'))rx.deleteCharAt(0);frame(f);}}
    private void frame(String f){try{Telemetry t=TelemetryParser.parse(f,System.currentTimeMillis());latest=t;long now=SystemClock.elapsedRealtime();if(pendingId.length()>0){if(Math.abs(t.chamberSetpoint-pendingValue)<.01){ack(pendingId,"set_temp",true,"applied",pendingValue);pendingId="";}else if(now-pendingSince>6000){ack(pendingId,"set_temp",false,"controller_ack_timeout",pendingValue);pendingId="";}}if(autoRunning()){AutoEngine.Update u=engine.onTelemetry(t,now);autoText=u.message;commands(u.commands);if(engine.getState()!=AutoEngine.State.RUNNING){main.removeCallbacks(heartbeat);stopForeground(true);maybeStop();}}publish(t);main.post(new Runnable(){public void run(){emit();}});}catch(final Exception e){error="Пакет: "+msg(e);main.post(new Runnable(){public void run(){emit();}});}}
    private void publish(Telemetry t){MqttClient m=mqtt;if(m==null||!m.isConnected())return;try{JSONObject o=new JSONObject();o.put("v",2);o.put("ts",t.receivedAtMs);o.put("temp_ds",t.chamber);o.put("temp_tip_k",t.probeK);o.put("temp_tip_t",t.probeT);o.put("temp_k",t.chamberSetpoint);o.put("heater_power",t.heaterPower);o.put("mode",t.mode);o.put("last_command",t.lastCommand);o.put("status",t.lastCommand);o.put("android_auto_running",autoRunning());o.put("android_auto_stage",engine.getStageIndex()+1);o.put("android_auto_status",autoText);m.publish(statusTopic(),o.toString(),true);}catch(Exception ignored){}}
    private void ack(String id,String cmd,boolean ok,String state,double value){MqttClient m=mqtt;if(m==null||!m.isConnected())return;try{JSONObject o=new JSONObject();o.put("v",2);o.put("id",id);o.put("ts",System.currentTimeMillis());o.put("cmd",cmd);o.put("ok",ok);o.put("state",state);o.put("message",state);if(!Double.isNaN(value))o.put("value",value);m.publish(ackTopic(),o.toString(),false);}catch(Exception ignored){}}
    private boolean commands(List<String>x){for(String s:x)if(!send(s))return false;return true;}private boolean send(String cmd){BluetoothSocket s=socket;if(s==null||!s.isConnected())return false;try{synchronized(this){s.getOutputStream().write((cmd+END).getBytes(UTF8));s.getOutputStream().flush();}return true;}catch(Exception e){error="BT send: "+msg(e);closeBtInternal();return false;}}
    private void abort(String why){main.removeCallbacks(heartbeat);commands(engine.stop(why).commands);autoText=why;stopForeground(true);main.post(new Runnable(){public void run(){emit();maybeStop();}});}private void closeBt(){closeBtInternal();btName="";}private void closeBtInternal(){BluetoothSocket s=socket;socket=null;if(s!=null)try{s.close();}catch(Exception ignored){}Thread t=btThread;btThread=null;if(t!=null&&t!=Thread.currentThread())t.interrupt();}
    private Notification notification(){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=new Notification.Builder(this).setSmallIcon(android.R.drawable.ic_lock_idle_alarm).setContentTitle("HomeSmoke Auto").setContentText(autoText).setOngoing(true).setContentIntent(pi);return Build.VERSION.SDK_INT>=16?b.build():b.getNotification();}
    private State snap(){return new State(btConnected(),mqttConnected(),btName,mqttText,autoText,error,latest,engine.getState());}private void emit(){if(autoRunning()){try{((android.app.NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(NOTIFY,notification());}catch(Exception ignored){}}Listener l=listener;if(l!=null)l.onState(snap());}private void maybeStop(){if(!client&&!autoRunning()&&!mqttWanted)stopSelf();}
    private String statusTopic(){return topic("topic","homesmoke/status");}private String cmdTopic(){return topic("cmd_topic","homesmoke/cmd");}private String ackTopic(){return topic("ack_topic","homesmoke/ack");}private String topic(String k,String d){String s=prefs.getString(k,d);return s==null||s.trim().length()==0?d:s.trim();}private static String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    @Override public void onDestroy(){main.removeCallbacks(heartbeat);main.removeCallbacks(mqttHealth);if(autoRunning()){send("a3");send("x0");}closeBtInternal();if(mqtt!=null)mqtt.close();super.onDestroy();}
}
